
# The configurations of surfex_dim_convert.py 

[conf_surfex_dim_convert]

#
# User Definations
#

# Choose: 
# MUMS      500m:     NorCP_ERAI_ALD_AROME, NorCP_ALADIN_ERAI, 
# GreenWave 300m: HCLIM38_Summer2018_STKHM_NEW, HCLIM38_Summer2018_STKHM_NEW_defaultPhys
#HCLIMEXP='NorCP_ERAI_ALD_AROME'
#HCLIMEXP='NorCP_ALADIN_ERAI'
#HCLIMEXP: HCLIM38_Summer2018_STKHM_NEW
#HCLIMEXP: HCLIM38_Summer2018_STKHM_NEW_defaultPhys
#HCLIMEXP: HCLIM38_Summer2018_STKHM_NEWphys
#HCLIMEXP: HCLIM38_Summer2018_STKHM_DEFphys
#HCLIMEXP: HCLIM38_Summer2018_STKHM_2050phys
#HCLIMEXP: HCLIM43_BRIGHT_Stockholm
HCLIMEXP: HCLIM43_BRIGHT_NorrLink

# SURFEX offline experiment name. 
# Choose: 
# MUMS
#SURFEXEXP: SCAN_ML_ROCK_initcorr'
#SURFEXEXP: SCAN_ML_ROCK_ini_rimax1'
#SURFEXEXP: SCAN_ML_ini_rimax1'
# GreenWave wrong:
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEW_ml55
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEW
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEW_defaultPhys_ml55
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_Default_HCLIMNew_ml65
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_Default_HCLIMDefault_ml65
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEW_defaultPhys_ml62
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEW_ml62
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEW_HCLIMDefault_ml65
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEW_HCLIMNew_ml65
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEW_HCLIMDefault_ml50m
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEW_HCLIMNew_ml50m
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_Default_HCLIMNew_50m
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_Default_HCLIMDefault_50m

# GreenWave correct:
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMR_mlL62
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMR_ml50m
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_DEFphs_HCLIMR_ml50m
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_DEFphs_HCLIMF_mlL62
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_2050phs_HCLIMD_mlL65

# GreenWave Paper Review
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMR_ml50m_to_50m
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMR_ml50m_to_L65
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMR_ml50m_to_L62
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMR_mlL65_to_50m
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMR_mlL62_to_50m
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMD_ml50m_to_L65
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMD_ml50m_to_L62
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMD_mlL62_to_50m
#SURFEXEXP: SURFEX73_GreenWave_300m_SCAY_ML_Summer2018_STKHM_NEWphs_HCLIMD_mlL65_to_50m

# BRIGHT
#SURFEXEXP: EV1_PGW1,EV1_PGW2,EV1_PGW3,EV2_PGW1,EV2_PGW2,EV2_PGW3,EV3_PGW1,EV3_PGW2,EV3_PGW3
SURFEXEXP: EV2_PGW1,EV2_PGW2,EV2_PGW3,EV3_PGW1,EV3_PGW2,EV3_PGW3
#SURFEXEXP: zref_default_90s
#SURFEXEXP: zref_default

# SURFEX 1D files
#name_surfex_file: SURF_ATM.OUT
#name_surfex_file: SURF_ATM_DIAGNOSTICS.OUT
#name_surfex_file: TEB_PROGNOSTIC.OUT,ISBA_DIAGNOSTICS.OUT,SEAFLUX_DIAGNOSTICS.OUT,FLAKE_DIAGNOSTICS.OUT,TEB_DIAGNOSTICS.OUT
#name_surfex_file: TEB_DIAGNOSTICS.OUT
#name_surfex_file: SURF_ATM.OUT,SURF_ATM_DIAGNOSTICS.OUT,TEB_DIAGNOSTICS.OUT,ISBA_DIAGNOSTICS.OUT,SEAFLUX_DIAGNOSTICS.OUT,FLAKE_DIAGNOSTICS.OUT
#name_surfex_file: SURF_ATM_DIAGNOSTICS.OUT,TEB_DIAGNOSTICS.OUT,ISBA_DIAGNOSTICS.OUT,SEAFLUX_DIAGNOSTICS.OUT,FLAKE_DIAGNOSTICS.OUT 

#name_surfex_file: ISBA_DIAG_CUMUL.OUT
name_surfex_file: ISBA_PROGNOSTIC.OUT
#name_surfex_file: TEB_CANOPY.OUT
#name_surfex_file: TEB_PROGNOSTIC.OUT
#name_surfex_file: SEAFLUX_DIAGNOSTICS.OUT,FLAKE_DIAGNOSTICS.OUT
#name_surfex_file: ISBA_VEG_EVOLUTION.OUT
#name_surfex_file: MUMS_FORCING_SCA_ZERO_2018070100_2018070524
