#!/bin/bash

# Copied from HCLIM scr/Prepare_pgd
# /home/sm_isari/hm_home/GreenWave/GreenWave_HCLIM38_currentVmergedUrbSIS_NorCP_Summer2018_STKHM_NEW/scr/Prepare_pgd

####################################
# No climate file found, create it #
####################################


# Orography input
YTOPO="gtopo30 "


# Soil texture data
case $SOIL_TEXTURE_VERSION in	
 FAO)
   YSAND="sand_fao"
   YCLAY="clay_fao"
   ;;
 HWSD_v2)
   YSAND="SAND_HWSD_MOY_v2"
   YCLAY="CLAY_HWSD_MOY_v2"
   ;;
 *)
   echo "No such option for SOIL_TEXTURE_VERSION: ${SOIL_TEXTURE_VERSION}"
   exit 1
   ;;
esac

# Land use 
case $ECOCLIMAP_VERSION in	
 1.0|1.2|1.3|1.4|1.5)
   YCOVER="ECOCLIMAP_I_GLOBAL_V${ECOCLIMAP_VERSION}"
   ;;
 2.0|2.1|2.2)
   YCOVER="ECOCLIMAP_II_EUROP_V${ECOCLIMAP_VERSION}"
   ;;
 *)
   echo "No such option for ECOCLIMAP_VERIONS: $ECOCLIMAP_VERSION"
   exit 1
   ;;
esac

PGD_FILES="$YTOPO $YSAND $YCLAY $YCOVER"

# Check and link the input data
for PGD_FILE in $PGD_FILES ; do
  for PGD_TYPE in hdr dir ; do
   FILE=$PGD_DATA_PATH/$PGD_FILE.$PGD_TYPE
   [[ -s $FILE ]] || { echo "Could not find $FILE" ; exit 1 ; }
   ln -s $FILE .
  done
done

# FLake files
FLAKE_FILES="GlobalLakeStatus GlobalLakeDepth"
FLAKE_INIT="LAKE_LTA_NEW.nc"

# Check and link the input data
FILE=$PGD_DATA_PATH/$FLAKE_INIT
[[ -s $FILE ]] || { echo "Could not find $FILE" ; exit 1 ; }
ln -s $FILE .

for FLAKE_FILE in $FLAKE_FILES ; do
  for PGD_TYPE in hdr dir ; do
   FILE=$PGD_DATA_PATH/$FLAKE_FILE.$PGD_TYPE
   [[ -s $FILE ]] || { echo "Could not find $FILE" ; exit 1 ; }
   ln -s $FILE .
  done
done

# Soil Organic Carbon files (SOC)

SOC_FILES="soc_top soc_sub"

for SOC_FILE in $SOC_FILES ; do
  for PGD_TYPE in hdr dir ; do
   FILE=$PGD_DATA_PATH/$SOC_FILE.$PGD_TYPE
   [[ -s $FILE ]] || { echo "Could not find $FILE" ; exit 1 ; }
   ln -s $FILE .
  done
done

# Creat OUTPUT_DIR
if [ ! -e $CLIMDIR/*.bin ] ; then
    echo "Could not find $CLIMDIR/*.bin, change CLIMDIR in simulation.def"
    exit 1 
else
    ln -sf $CLIMDIR/*.bin .
fi

# Additional urban physiography specifications for surfex
if [ $SURFEX_URBAN_SPEC = "urban" ] ; then
 ln -s $PGD_DATA_PATH/*.dat .  
 rm ecoclimap*.dat
fi

#exit
